{{- if .Values.dockerRegistry.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "docker-registry" .Values.dockerRegistry.secretName }}
  labels:
    {{- include "digital-contracting-service.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .Values.dockerRegistry.server .Values.dockerRegistry.username .Values.dockerRegistry.password (printf "%s:%s" .Values.dockerRegistry.username .Values.dockerRegistry.password | b64enc) | b64enc }}
{{- end }}
