apiVersion: v1
kind: Service
metadata:
  name: fc-keycloak-http
  labels:
    app.kubernetes.io/name: fc-keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      {{- if and .Values.service.nodePort (eq (.Values.service.type | default "ClusterIP") "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: fc-keycloak
    app.kubernetes.io/instance: {{ .Release.Name }}
