apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgresql
type: Opaque
stringData:
  postgres-user: {{ .Values.auth.username | quote }}
  postgres-password: {{ .Values.auth.password | quote }}
  postgres-database: {{ .Values.auth.database | quote }}
