apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nats
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nats
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: nats
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ["-js"]
          ports:
            - name: client
              containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
