apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nats
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - name: client
      port: {{ .Values.service.port }}
      targetPort: client
      {{- if and (eq (.Values.service.type | default "ClusterIP") "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: nats
    app.kubernetes.io/instance: {{ .Release.Name }}
